### PR TITLE
Replace tests in EdgeR analysis.

### PR DESCRIPTION
**Pull request by JasperBoom**

### CODE REVIEW

**Comment by DavyCats** [comment]
Maybe this should be a new option. Instead of replacing the LRT one. @hailiangmei ?

**Comment by JasperBoom** [comment]
> Maybe this should be a new option. Instead of replacing the LRT one. @hailiangmei ?

I was wondering this myself as well, let users choose between the tests when they select EdgeR.

**Comment by hailiangmei** [comment]
I think we should just replace it since edgeR manual also recommend the use of glmQLFit and Test for bulk RNAseq data which is the main objective of our shinyapp.

**Comment by JasperBoom** [comment]
This PR was addressed with this https://github.com/LUMC/dgeAnalysis/commit/f8c26abcd9fba519c606d021977354e4f2de9eb9 commit by @DavyCats

**Pull request closed without merging**
